### ISSUE TITLE
The page required does not exist.

### ISSUE THREAD

**Issue by prasadtakale** [IamFive/python-ibmcclient#2]
When try to connect to iBMC server getting below Traceback.

iBMC response -> GET http://172.16.24.205//redfish/v1, code: 404, response: b'The page required does not exist.'
Error response from GET http://172.16.24.205//redfish/v1 with status code 404 has no JSON body
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ibmc_client/connector.py", line 155, in request
    headers=headers)
  File "/usr/lib/python3.6/site-packages/ibmc_client/connector.py", line 210, in _request
    res.raise_for_status()
  File "/usr/lib/python3.6/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://172.16.24.205//redfish/v1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ibmc_config.py", line 15, in <module>
    with ibmc_client.connect(address, username, password, verify) as client:
  File "/usr/lib/python3.6/site-packages/ibmc_client/__init__.py", line 32, in connect
    return IBMCClient(address, username, password, verify_ca)
  File "/usr/lib/python3.6/site-packages/ibmc_client/__init__.py", line 43, in __init__
    self.connector = Connector(address, username, password, verify_ca)
  File "/usr/lib/python3.6/site-packages/ibmc_client/connector.py", line 50, in __init__
    self._meta = self.request(constants.GET, self.base_url).json()
  File "/usr/lib/python3.6/site-packages/ibmc_client/connector.py", line 178, in request
    raise exceptions.raise_for_response(method, url, response)
  File "/usr/lib/python3.6/site-packages/ibmc_client/exceptions.py", line 230, in raise_for_response
    raise ResourceNotFoundError(method, url, response)
ibmc_client.exceptions.ResourceNotFoundError: Resource http://172.16.24.205//redfish/v1 not found

**Comment by IamFive** [comment]
There got an extra "/" in your endpoint.  The address should not contain the end "/", it should be "http://172.16.24.205" in your case.

**Comment by prasadtakale** [comment]
> There got an extra "/" in your endpoint. The address should not contain the end "/", it should be "http://172.16.24.205" in your case.

Still having same error. 

iBMC response -> GET http://172.16.24.205/redfish/v1, code: 404, response: b'The page required does not exist.'
Error response from GET http://172.16.24.205/redfish/v1 with status code 404 has no JSON body
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ibmc_client/connector.py", line 155, in request
    headers=headers)
  File "/usr/lib/python3.6/site-packages/ibmc_client/connector.py", line 210, in _request
    res.raise_for_status()
  File "/usr/lib/python3.6/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://172.16.24.205/redfish/v1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ibmc_config.py", line 15, in <module>
    with ibmc_client.connect(address, username, password, verify) as client:
  File "/usr/lib/python3.6/site-packages/ibmc_client/__init__.py", line 32, in connect
    return IBMCClient(address, username, password, verify_ca)
  File "/usr/lib/python3.6/site-packages/ibmc_client/__init__.py", line 43, in __init__
    self.connector = Connector(address, username, password, verify_ca)
  File "/usr/lib/python3.6/site-packages/ibmc_client/connector.py", line 50, in __init__
    self._meta = self.request(constants.GET, self.base_url).json()
  File "/usr/lib/python3.6/site-packages/ibmc_client/connector.py", line 178, in request
    raise exceptions.raise_for_response(method, url, response)
  File "/usr/lib/python3.6/site-packages/ibmc_client/exceptions.py", line 230, in raise_for_response
    raise ResourceNotFoundError(method, url, response)
ibmc_client.exceptions.ResourceNotFoundError: Resource http://172.16.24.205/redfish/v1 not found

**Comment by IamFive** [comment]
Can you visit  http://172.16.24.205/redfish/v1 directly on your browser.?
Have you tried to use https and set verify_ca to False?

**Comment by prasadtakale** [comment]
> http://172.16.24.205/redfish/v1

Working now with https and varify_ca with false.
